config/routes.rb
Rails.application.routes.draw do

  get 'courses/destroy'

  get 'courses/create'

  get 'courses/edit'

  get 'courses/update'

  root to: 'users#index'

  devise_for :users, :singular => :user
  scope "/dashboard" do
    resources :users, except: :edit
    resources :enrollments
    resources :courses
  end
  
  get '/dashboard/users/edit/:id' => 'users#edit', as: :edit_user

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  owner_id    :integer
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Course < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
	has_many :enrollments
	has_many :users, :through => :enrollments

	belongs_to :owner, class_name: :User
    
end

app/models/enrollment.rb
# == Schema Information
#
# Table name: enrollments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  course_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Enrollment < ActiveRecord::Base
    belongs_to :user
	belongs_to :course
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  username               :string
#

class User < ActiveRecord::Base

	has_many :enrollments
	has_many :courses, :through => :enrollments

	has_many :admin_courses, foreign_key: :owner_id , class_name: "Course"
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	def enrolled?(course)
		courses_ids_array = self.courses.pluck(:id)
		courses_ids_array.include?(course.id)
  	end
  	def creator?(course)
  		courses_ids_array = self.admin_courses.pluck(:id)
		courses_ids_array.include?(course.id)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def destroy
  	course = Course.find(courses_parameters[:id])
  	course.destroy
  	redirect_to :controller => "users", :action => "show"
  end

  def create
  	course = Course.new(owner_id: create_courses_parameters[:owner_id], name: create_courses_parameters[:name], description: create_courses_parameters[:description])
    if course.save
      redirect_to :controller => "users", :action => "index"
    else
      flash[:error] = course.errors
      redirect_to :controller => "users" , :action => "new"

    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
  end
  private
  def courses_parameters
  	params.require(:course).permit(:id)
  end
  def create_courses_parameters
  	params.require(:course).permit(:description, :owner_id, :name)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	def create 	#post , params[:article]
		enrollment = Enrollment.new(enrollment_parameters)
		enrollment.save!
		redirect_to :controller => 'users', :action => 'index'
	end
	def destroy #delete

		enrollment = Enrollment.where(user_id: enrollment_parameters[:user_id], course_id: enrollment_parameters[:course_id]).take
		#@enrollment = enrollment.class
		enrollment.destroy
		redirect_to :controller => 'users', :action => 'index'
	end

	private
	def enrollment_parameters
		params.require(:enrollment).permit(:user_id,:course_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except:[:index]
	def index   #get
		unless user_signed_in?
			render "index"
		else
			# byebug
			@courses = Course.all
			render "index_admin"
		end
	end
	def new 	#get
		@current_user = current_user
		@course = Course.new()
	end
	def create 	#post

	end
	def show 	#get
		user = current_user
		@courses = user.admin_courses
	end
	def edit 	#get

	end
	def update 	#put/patch
	end
	def destroy #delete
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form_courses.html.erb
<div class="ui three column centered grid">
	<div class="column"></div>
	<div class="column">
		<%= form_for @course, url: courses_path(@course), html: {class: "ui warning form segment"} do |f| %>
			<% if flash[:error] %>
				<div id="error_explanation" class="ui warning message">
				    <h2 class='header'> Could you check something!</h2>
				    <ul class="list">
				    <% flash[:error].map do |message|%>
				      <li><%= message %></li>
				    <% end %>
				    </ul>
				</div>
			<% end %>
			<div class="ui raised segment">
				<a class="ui ribbon label">Create a Course!</a>
				<p></p>
				<%=f.hidden_field(:owner_id,value: current_user.id)%>
				<div class="field">
					<label>Course's name</label>
					<%= f.text_field :name, value: "#{@course.name}" %>
				</div>
				<div class="field">
					<label>Description</label>
					<%= f.text_area :description, value: "#{@course.description}" %>
				</div>
				<%= f.submit(class: "ui blue submit button") %>
				<div class="ui error message"></div>
			</div>
		<%end%>
	</div>
	<div class="column"></div>
</div>

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

app/views/courses/edit.html.erb
<%=  render partial: "users/header_admin" %>
<%=  render "form_courses" %>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>

app/views/enrollments/create.html.erb
<h1>Enrollmentss#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/enrollments/destroy.html.erb
<h1><%=@enrollment%>#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Udemi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="ui menu inverted navbar page grid" style="margin-bottom: 0px">
		<%= link_to "Udem'I'", root_path, class: 'brand item'%>
        <div class="right menu">
            <% if user_signed_in? %>
                <div class="item">
                    <div class="ui white button">Signed in as <%= current_user.username %>.</div>
                </div>
                <div class="item">
                    <span class='pointing finger'>Not you?    </span>
                    <%= link_to "Sign out", destroy_user_session_path, :method => :delete,class: 'ui red button' %>
                </div>
                
                
              <% else %>
                <div class="item">
                    <%= link_to "Login in",new_user_session_path, class: 'ui green button' %> 
                </div>
                <div class="item">
                    <%= link_to "sign up", new_user_registration_path, class: 'ui blue button'%>    
                </div>
                
                
              <% end %>
                
        </div>
    </nav>
<%= yield %>
	
</body>
</html>

app/views/users/1new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/_header_admin.html.erb
<div class="ui tabular menu">
	<%= link_to "All the courses", users_path, class: ' item' %>
	<%= link_to "My List", user_path(current_user), class: 'item' %> 
	<%= link_to "Create", new_user_path(current_user), class: 'item' %> 
	<%= link_to "Update", users_path, class: 'item' %> 
</div>

app/views/users/_list.html.erb
<div class="ui page grid">
	<% if !@courses.blank? %>
	<% @courses.map do |course|  %>
		<%unless @current_user.creator?(course) %>
			<div class="row">
				<div class="column">
					<h2 class="ui header"><%= course.name %></h2>
					<p><%= course.description %></p>
					<div class="ui column centered grid">
						<%if @current_user.enrolled?(course) %>
							<%= form_for :enrollment,html:{class:'column'}, url: enrollment_path(@current_user),
							method: :delete do |f| %>
								<%=f.hidden_field(:user_id, value:"#{current_user.id}")%>
								<%=f.hidden_field(:course_id, value:"#{course.id}")%>
								<button class="ui tiny orange button m-top-10">disincorporate »</button>
							<%end%>
						<%else%>
							<%= form_for :enrollment,html:{class:'column'}, url: { controller: "enrollments",action: "create" } do |f| %>
								<%=f.hidden_field(:user_id, value:"#{current_user.id}")%>
								<%=f.hidden_field(:course_id, value:"#{course.id}")%>
								<button class="ui tiny green button m-top-10">Enroll »</button>
							<%end%>
						<%end%>
					</div>
				</div>
			</div>
		<%end%>
	<% end %>
	<% else %>
		<div class="row">
			<div class="column">
				<h2 class="ui header">You do not have any courses registered at your name</h2>
				<p>if you want to register a new course tap the tab <strong>create</strong></p>
			</div>
		</div>
	<% end %>

	<div class="row">
		<div class="column">
			<div class="ui divider"></div>  
			<span>© Jasmo2, 2015</span>
		</div>
	</div>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<div class="ui grid">
    <div class="row">
        <div class="column padding-reset">
            <div class="ui huge message page grid">
                <h1 class="ui huge header">Welcome to Udem'I'</h1>
                <p>This webpage is a Rookie clone of <a target="_blank" href="https://www.udemy.com/">Udemy</a></p>
            </div>
        </div>
    </div>
</div>
 

app/views/users/index_admin.html.erb
<%= render 'header_admin' %>
<%= render 'list' %>

app/views/users/new.html.erb
<%= render 'header_admin' %>
<%= render partial: 'courses/form_courses' %>

app/views/users/show.html.erb
<%= render 'header_admin' %>

<div class="ui page grid">
	<% if !@courses.blank? %>
	<% @courses.map do |course|  %>
	<div class="row">
		<div class="column">
			<h2 class="ui header"><%= course.name %></h2>
			<p><%= course.description %></p>
			<div class="ui five column  grid">
				<%= form_for :course,html:{class:'column'}, url: course_path(@current_user), method: :delete do |f| %>
					<%=f.hidden_field(:id, value:"#{course.id}")%>
					<button class="ui tiny red button m-top-10">Delete Course »</button>
				<%end%>
				<div class="column">
					<%=link_to "Edit »", edit_course_path(course), class: "ui tiny pink button m-top-10"%>
				</div>
				<div class="column"></div>
				<div class="column"></div>
				<div class="column"></div>
			</div>
		</div>
	</div>
	<% end %>
	<% else %>
		<div class="row">
			<div class="column">
				<h2 class="ui header">You do not have any courses registered at your name</h2>
				<p>if you want to register a new course tap the tab <strong>create</strong></p>
			</div>
		</div>
	<% end %>

	<div class="row">
		<div class="column">
			<div class="ui divider"></div>  
			<span>© Jasmo2, 2015</span>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>